### ISSUE TITLE
Module not found: Error: Can't resolve '@textile/ipfs-lite'

### ISSUE THREAD

**Issue by ethernomad** [textileio/js-ipfs-lite#16]
package.json has "main": "dist/index.js" But this file is not in the package and is not being automatically built.

**Comment by carsonfarmer** [comment]
Hi @ethernomad, can you tell me more about your install setup? Running something like:

```
mkdir test
cd test
npm init
npm i @textile/ipfs-lite
```

Seems to work ok for me? Do you have scripts disabled with npm maybe? We have a `prepare` step that should compile the Typescript sources into Javascript in a `dist` folder on install (https://docs.npmjs.com/misc/scripts). Also, which version of `@textile/ipfs-lite` have you installed? There might be an issue with `v0.1.0`?

**Comment by ethernomad** [comment]
I have quite a complicated setup. My app is built for both electron and web so that is probably where the issue is coming from.

I actually switched to js-ipfs because I need the full node functionality in browser.
