### ISSUE TITLE
Start pulling in all the new types...

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-ipfs-lite#59]
- multibase https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41416
- multiaddr https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41413
- multicodec https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41404
- exicographic-integer https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41025
- datastore-core https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41011
- datastore-level https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40932
- level-ttl https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40931
- interface-datastore https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40842
- levelup https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40792
- sublevel-down https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40754
- https://github.com/ipfs/js-datastore-level/pull/25
- https://github.com/multiformats/js-cid/pull/94

**Comment by AuHau** [comment]
WOW this is super awesome! 
Thanks a lot for this @carsonfarmer!

**Comment by carsonfarmer** [comment]
Ok, closing this as we're mostly done with this for now.
