### ISSUE TITLE
Switch to a single PR template that works for all types of PRs so that you can use it without copying and pasting

### ISSUE THREAD

**Issue by pcowgill** [textileio/js-ipfs-lite#87]
**Is your feature request related to a problem? Please describe.**
It's extra work to copy and paste a PR template of a certain type when GitHub has a feature to click a button and use the right template directly.

**Describe the solution you'd like**
I would like a button added when someone creates a PR so that they can click on the type of template they would like to use.

**Describe alternatives you've considered**
Status quo

**Additional context**
n/a

**Comment by carsonfarmer** [comment]
Ah, this nice clicky feature is only nicely exposed on GitHub if you use a _single_ PR template. So we should just do that. I'll combine the 3 we have into one. Thanks for the suggestion @pcowgill.

**Comment by pcowgill** [comment]
Oh, maybe it’s issues that allow for multiple clickable templates

**Comment by carsonfarmer** [comment]
It is indeed. Too bad 🤷‍♂. Oh well... One is fine too.
